### ISSUE TITLE
Can you hack into the system and get the clock-in time directly?

### ISSUE THREAD

**Issue by demoManito** [SeigeC/go-home#2]

**Comment by SeigeC** [comment]
I think you can do it

**Comment by demoManito** [comment]
> I think you can do it

I can't, you can

**Comment by SeigeC** [comment]
You are the CTO.  This work only CTO can do

**Comment by demoManito** [comment]
> You are the CTO. This work only CTO can do

No, no, no, you are the CTO and CEO, the more capable (SeigeC) should work harder
